---

- name: Install OpsCenter agents
  yum:
    name: datastax-agent
    state: present
  become: yes

- name: Template address.yaml file
  template:
    src: ./templates/address.yaml.j2
    dest: "/var/lib/datastax-agent/conf/address.yaml"
    owner: "{{ owner }}"
    group: "{{ group }}"
    backup: yes
  become: yes
